// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6OHpn8zxzdYxza_tcmrXtZxmEYgxtzXI',
    appId: '1:169464391961:web:679f85553e08d09b08bd88',
    messagingSenderId: '169464391961',
    projectId: 'oamenibuni-3e101',
    authDomain: 'oamenibuni-3e101.firebaseapp.com',
    storageBucket: 'oamenibuni-3e101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJwSd66HW1bcnTIKiAUO3THTV28g4mJas',
    appId: '1:169464391961:android:1836ee4f9fa8c59e08bd88',
    messagingSenderId: '169464391961',
    projectId: 'oamenibuni-3e101',
    storageBucket: 'oamenibuni-3e101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZASF_gwM0HrG7MRo3sRMNHDAn0tcNmw',
    appId: '1:169464391961:ios:07308cd9f8ebf10508bd88',
    messagingSenderId: '169464391961',
    projectId: 'oamenibuni-3e101',
    storageBucket: 'oamenibuni-3e101.appspot.com',
    iosBundleId: 'com.example.bestPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOZASF_gwM0HrG7MRo3sRMNHDAn0tcNmw',
    appId: '1:169464391961:ios:07308cd9f8ebf10508bd88',
    messagingSenderId: '169464391961',
    projectId: 'oamenibuni-3e101',
    storageBucket: 'oamenibuni-3e101.appspot.com',
    iosBundleId: 'com.example.bestPeople',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6OHpn8zxzdYxza_tcmrXtZxmEYgxtzXI',
    appId: '1:169464391961:web:8e9e9a9fe41a3f1f08bd88',
    messagingSenderId: '169464391961',
    projectId: 'oamenibuni-3e101',
    authDomain: 'oamenibuni-3e101.firebaseapp.com',
    storageBucket: 'oamenibuni-3e101.appspot.com',
  );

}